services:
  backend:
    image: hermesndj/vhs-analyzer-backend:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    env_file: .env
    volumes:
      - models:/app/models
    restart: unless-stopped

  frontend:
    image: hermesndj/vhs-analyzer-frontend:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  models:
